export const links = [
  { name: "Home", hash: "#home" },
  { name: "About", hash: "#about" },
  { name: "Work", hash: "#work" },
  { name: "Skills", hash: "#skills" },
  { name: "Experience", hash: "#experience" },
  { name: "Contact", hash: "#contact" },
] as const;

export const socials = [
  { name: "LinkedIn", href: "https://www.linkedin.com/in/erikhein/" },
  { name: "GitHub", href: "https://github.com/erik-ksth" },
  { name: "YouTube", href: "https://www.youtube.com/@erik-hein" },
  { name: "Behance", href: "https://www.behance.net/kaungsithu32" },
] as const;

export const email = "erikhein.ksth@gmail.com";

export const experiencesData = [
  {
    title: "Full-stack Developer / Founder",
    location: "Solariz Studio LLC",
    date: "May 2026 - present",
  },
  {
    title: "Software Engineer",
    location: "Iditor Inc.",
    date: "Sep 2024 - present",
  },
  {
    title: "Software Development Engineer Intern",
    location: "Graph Academy",
    date: "May 2024 - Sep 2024",
  },
  {
    title: "Bachelor's Degree in Computer Science",
    location: "San José State University",
    date: "2023 - 2025",
  },
  {
    title: "Front-End Developer & UI/UX Designer",
    location: "Bridge Burma",
    date: "Aug 2023 - Nov 2024",
  },
  {
    title: "Web Development Intern",
    location: "Oakmead Printing Inc.",
    date: "Sep 2023 - Nov 2023",
  },
  {
    title: "Associate's Degree for Transfer in Computer Science",
    location: "De Anza College",
    date: "Jun 2023",
  },
  {
    title: "Co-Founder and Project Leader",
    location: "Robotics Society of De Anza",
    date: "Mar 2022 - Oct 2022",
  },
] as const;

// `image` points at the 1280px textures in /public/work, sized for WebGL.
export const projectsData = [
  {
    title: "Jade AI",
    subtitle: "Conversational Data Analyst",
    description:
      "Winner, Best Use of Groq at Cal Hacks 12.0. An AI data analyst for messy spreadsheets: describe the fix in plain English, and a LangGraph workflow writes and runs the pandas code, then charts the result.",
    tags: ["Next.JS", "Python", "Fast API", "Pandas"],
    image: "/work/jadeAi.jpg",
    link: "https://jade-ai-landing.vercel.app",
  },
  {
    title: "Trekteria",
    subtitle: "AI-Powered Camping Planner",
    description:
      "AI-powered camping planner that generates personalized itineraries based on user preferences and location.",
    tags: ["React Native", "Expo", "Supabase", "Mobile App"],
    image: "/work/trekteria.jpg",
    link: "https://trekteria.com/",
  },
  {
    title: "YT Commerizer",
    subtitle: "Video Insight Extension",
    description:
      "A browser extension that analyzes YouTube videos and provides a sentiment analysis and summary of the video.",
    tags: ["Chrome Extension", "Node.js", "React", "Vite", "Generative AI", "GCP"],
    image: "/work/ytCommerizer.jpg",
    link: "https://chromewebstore.google.com/detail/ejbelaeciihalcbaikocbheoefhikicb?utm_source=item-share-cb",
  },
  {
    title: "Type In Zen",
    subtitle: "Relaxing Typing Game",
    description:
      "A zen, calming typing game with relaxing ambient sounds. The content is generated by AI.",
    tags: ["React", "Generative AI", "JavaScript", "Web App"],
    image: "/work/typeInZen.jpg",
    link: "https://typeinzen.vercel.app/",
  },
  {
    title: "Study Buddy",
    subtitle: "Productivity Companion",
    description:
      "A web app to boost productivity: Pomodoro timer, to-do list, ambient sounds and music, and inspirational quotes from famous people.",
    tags: ["HTML", "CSS", "JavaScript", "JQuery"],
    image: "/work/studybuddy.jpg",
    link: "https://study-buddy.vercel.app/",
  },
] as const;

export const skillsData = [
  "C++",
  "Java",
  "Python",
  "JavaScript",
  "TypeScript",
  "Dart",
  "Prisma",
  "HTML",
  "CSS",
  "Bootstrap",
  "React",
  "React Native",
  "Next.js",
  "Node.js",
  "Flutter",
  "JavaFX",
  "API",
  "Git",
  "Arduino",
  "Tailwind",
  "MySQL",
  "PostgreSQL",
  "Supabase",
  "SQLite",
  "MongoDB",
  "Firebase",
  "Google AI Cloud",
  "Wordpress",
  "Framer Motion",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe XD",
  "Figma",
  "Expo",
  "FastAPI",
  "Lyria AI",
  "Groq",
  "Google ADK",
] as const;

export const skillsDataCategorized = [
  {
    category: "Languages",
    skills: ["C++", "Java", "Python", "JavaScript", "TypeScript", "Dart", "HTML", "CSS"],
  },
  {
    category: "Frontend",
    skills: ["React", "React Native", "Next.js", "Tailwind", "Bootstrap", "Framer Motion", "Expo", "JavaFX", "Flutter"],
  },
  {
    category: "Backend",
    skills: ["Node.js", "FastAPI", "Prisma", "API"],
  },
  {
    category: "Database",
    skills: ["MySQL", "PostgreSQL", "Supabase", "SQLite", "MongoDB", "Firebase"],
  },
  {
    category: "Tools & AI",
    skills: ["Git", "Arduino", "Google AI Cloud", "Lyria AI", "Groq", "Google ADK", "Wordpress"],
  },
  {
    category: "Design",
    skills: ["Adobe Photoshop", "Adobe Illustrator", "Adobe XD", "Figma"],
  },
] as const;
